# Generated by Django 4.2.7 on 2025-04-15 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='amount_paid',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='insurance_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='insurance_status',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
