version: '3.8'

services:
  db:
    image: postgres:14  # Use PostgreSQL 14 to match existing data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=healthcare_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthcare_network

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    command: >
      bash -c "echo 'Waiting for database...' &&
              sleep 15 &&
              echo 'Creating necessary directories...' &&
              mkdir -p /app/staticfiles &&
              mkdir -p /app/mediafiles &&
              echo 'Setting up database...' &&
              python manage.py migrate --fake users.0001_initial &&
              python manage.py migrate &&
              echo 'Creating superuser...' &&
              python create_superuser.py &&
              echo 'Collecting static files...' &&
              python manage.py collectstatic --no-input &&
              echo 'Starting server...' &&
              gunicorn healthcare.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8080:8000"
    networks:
      - healthcare_network

networks:
  healthcare_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
