# Generated by Django 4.2.7 on 2025-04-14 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', 'add_read_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='notificationrecord',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notificationrecord',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('invoice', 'Invoice'), ('delivery', 'Delivery'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
