# Generated by Django 4.2.7 on 2025-04-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_alter_notificationrecord_options_and_more'),
        ('notification', 'add_title_field'),
    ]

    operations = [
    ]
