# Generated by Django 4.2.7 on 2025-04-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_merge_20250415_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notificationrecord',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='notificationrecord',
            name='target_url',
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
