# Generated by Django 4.2.7 on 2025-04-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_alter_notificationrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='notification_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
