# Generated by Django 4.2.7 on 2025-04-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('operating_hours', models.CharField(help_text='E.g., Mon-Fri: 9AM-6PM, Sat: 10AM-4PM', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('dispensed', 'Dispensed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_dispensings', to='prescription.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField(help_text='Restock when inventory falls below this level')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_restocked', models.DateField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='prescription.medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.pharmacylocation')),
            ],
            options={
                'verbose_name_plural': 'Medication Inventories',
                'unique_together': {('pharmacy', 'medication', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='MedicationDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL)),
                ('prescription_dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pharmacy.prescriptiondispensing')),
            ],
        ),
        migrations.CreateModel(
            name='DispensedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('dispensing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_items', to='pharmacy.prescriptiondispensing')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicationinventory')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescriptionitem')),
            ],
        ),
    ]
